import 'dart:convert';

/// Represents a structured navigation routing request generated by Aling Suki
class ChatRouteAction {
  final String originType; // 'entrance' | 'stall'
  final String? originId; // entrance number (e.g. '2') or origin stallId
  final String destinationStallId;
  final String? destinationStallName;

  const ChatRouteAction({
    required this.originType,
    this.originId,
    required this.destinationStallId,
    this.destinationStallName,
  });

  Map<String, dynamic> toJson() => {
        'originType': originType,
        if (originId != null) 'originId': originId,
        'destinationStallId': destinationStallId,
        if (destinationStallName != null)
          'destinationStallName': destinationStallName,
      };

  factory ChatRouteAction.fromJson(Map<String, dynamic> json) {
    return ChatRouteAction(
      originType: json['originType']?.toString().toLowerCase() == 'stall'
          ? 'stall'
          : 'entrance',
      originId: json['originId']?.toString(),
      destinationStallId: json['destinationStallId']?.toString() ?? '',
      destinationStallName: json['destinationStallName']?.toString(),
    );
  }

  /// Extracts ChatRouteAction from raw message text containing `<!--ROUTE:{...}-->`
  static ChatRouteAction? tryParseFromText(String text) {
    final match = RegExp(
      r'<!--ROUTE:\s*(\{.*?\})\s*-->',
      dotAll: true,
    ).firstMatch(text);

    if (match == null) return null;

    try {
      final jsonStr = match.group(1)!;
      final decoded = jsonDecode(jsonStr) as Map<String, dynamic>;
      final action = ChatRouteAction.fromJson(decoded);
      if (action.destinationStallId.trim().isNotEmpty) {
        return action;
      }
    } catch (_) {
      // Malformed or incomplete JSON tag
    }
    return null;
  }

  /// Strips the `<!--ROUTE:...-->` tag and any incomplete trailing route tags from displayed text
  static String stripRouteTags(String text) {
    var cleaned = text.replaceAll(
      RegExp(r'<!--ROUTE:\s*\{.*?\}\s*-->', dotAll: true),
      '',
    );
    // Also remove partially streamed unclosed tags at the end of the text
    cleaned = cleaned.replaceAll(RegExp(r'<!--ROUTE:.*$', dotAll: true), '');
    return cleaned.trimRight();
  }
}
