import 'dart:convert';

/// Represents a structured directory navigation request generated by Aling Suki
/// when a category has many stalls (> 5) or when user asks for all stalls.
class ChatDirectoryAction {
  final String category;
  final int totalCount;

  const ChatDirectoryAction({
    required this.category,
    required this.totalCount,
  });

  Map<String, dynamic> toJson() => {
        'category': category,
        'totalCount': totalCount,
      };

  factory ChatDirectoryAction.fromJson(Map<String, dynamic> json) {
    return ChatDirectoryAction(
      category: json['category']?.toString().trim() ?? '',
      totalCount: int.tryParse(json['totalCount']?.toString() ?? '0') ?? 0,
    );
  }

  /// Extracts ChatDirectoryAction from raw message text containing `<!--DIRECTORY:{...}-->`
  static ChatDirectoryAction? tryParseFromText(String text) {
    final match = RegExp(
      r'<!--DIRECTORY:\s*(\{.*?\})\s*-->',
      dotAll: true,
    ).firstMatch(text);

    if (match == null) return null;

    try {
      final jsonStr = match.group(1)!;
      final decoded = jsonDecode(jsonStr) as Map<String, dynamic>;
      final action = ChatDirectoryAction.fromJson(decoded);
      if (action.category.isNotEmpty) {
        return action;
      }
    } catch (_) {
      // Malformed or incomplete JSON tag
    }
    return null;
  }

  /// Strips the `<!--DIRECTORY:...-->` tag and any incomplete trailing directory tags from displayed text
  static String stripDirectoryTags(String text) {
    var cleaned = text.replaceAll(
      RegExp(r'<!--DIRECTORY:\s*\{.*?\}\s*-->', dotAll: true),
      '',
    );
    // Also remove partially streamed unclosed tags at the end of the text
    cleaned = cleaned.replaceAll(RegExp(r'<!--DIRECTORY:.*$', dotAll: true), '');
    return cleaned.trimRight();
  }
}
